### ISSUE TITLE
 [error] [0] Unable to Bypass  with ip:

### ISSUE THREAD

**Issue by MythicScythe** [forkyyy/http-browser#1]
error un able to bypass

what proxy do i need?
is it ip:port?

**Comment by NekoLoliOwO** [comment]
Wrong NodeJS version. You need NodeJS 16.X

**Comment by MythicScythe** [comment]
> 

just updated to 16.14.2 and its still not working

**Comment by NekoLoliOwO** [comment]
Hm.... Try to do that:

``cd solvers/flaresolver01; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver02; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver03; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver04; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver05; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver06; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver07; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver08; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver09; export PUPPETEER_PRODUCT=firefox; npm install; npm run
cd ../; cd flaresolver10; export PUPPETEER_PRODUCT=firefox; npm install; npm run``

after that execute

``cd solvers/flaresolver01; screen -AmdS solver1 npm start
cd ../; cd flaresolver02; screen -AmdS solver2 npm start
cd ../; cd flaresolver03; screen -AmdS solver3 npm start
cd ../; cd flaresolver04; screen -AmdS solver4 npm start
cd ../; cd flaresolver05; screen -AmdS solver5 npm start
cd ../; cd flaresolver06; screen -AmdS solver6 npm start
cd ../; cd flaresolver07; screen -AmdS solver7 npm start
cd ../; cd flaresolver08; screen -AmdS solver8 npm start
cd ../; cd flaresolver09; screen -AmdS solver9 npm start
cd ../; cd flaresolver10; screen -AmdS solver10 npm start ``

**Comment by MythicScythe** [comment]
> Hm.... Try to do that:
> 
> cd solvers/flaresolver01; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver02; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver03; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver04; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver05; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver06; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver07; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver08; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver09; export PUPPETEER_PRODUCT=firefox; npm install; npm run cd ../; cd flaresolver10; export PUPPETEER_PRODUCT=firefox; npm install; npm run
> 
> after that execute
> 
> cd solvers/flaresolver01; screen -AmdS solver1 npm start cd ../; cd flaresolver02; screen -AmdS solver2 npm start cd ../; cd flaresolver03; screen -AmdS solver3 npm start cd ../; cd flaresolver04; screen -AmdS solver4 npm start cd ../; cd flaresolver05; screen -AmdS solver5 npm start cd ../; cd flaresolver06; screen -AmdS solver6 npm start cd ../; cd flaresolver07; screen -AmdS solver7 npm start cd ../; cd flaresolver08; screen -AmdS solver8 npm start cd ../; cd flaresolver09; screen -AmdS solver9 npm start cd ../; cd flaresolver10; screen -AmdS solver10 npm start
> 
> This worked for me.

still not working same error

**Comment by 2697106714** [comment]
> 错误的 NodeJS 版本。你需要 NodeJS 16.X

What proxy are you using?

**Comment by Egida** [comment]
+ not working for me
[error] [0] Unable to Bypass

**Comment by bntr00t** [comment]
Dude...

**Comment by MythicScythe** [comment]
> > 错误的 NodeJS 版本。你需要 NodeJS 16.X
> 
> What proxy are you using?

it is http proxy ip:port but not say unable to bypass

**Comment by iLaravel** [comment]
You must have a valid proxy list

**Comment by MythicScythe** [comment]
> You must have a valid proxy list

yeah, still not working

**Comment by forkyyy** [comment]
Problem with tour server, this will be closed.

**Comment by Yariya** [comment]
buy proxies for 1000000000$ problem solved.
