### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by adultmovieactor** [forkyyy/http-browser#4]
![image](https://user-images.githubusercontent.com/104075270/164230334-cb79f253-327e-4529-81a0-25f560794e27.png)

**Comment by iLaravel** [comment]
fixed in https://github.com/NekoLoliOwO/http-browser

**Comment by adultmovieactor** [comment]
> fixed in https://github.com/NekoLoliOwO/http-browser

i used that source.

**Comment by adultmovieactor** [comment]
> 

![image](https://user-images.githubusercontent.com/104075270/164237383-ba74d38a-1dfc-4ae5-9dbd-456a4c0e2d80.png)

**Comment by Egida** [comment]
up

**Comment by adultmovieactor** [comment]
> up

?

**Comment by Egida** [comment]
> > up
> 
> ?

?

**Comment by adultmovieactor** [comment]
> > > up
> > 
> > 
> > ?
> 
> ?

i use the latest source that u said me to use still same error.

**Comment by forkyyy** [comment]
Proxies problem, case closed.
